import { addToCart } from '@/utils/cartStore';
import { AppScreen } from '@/components/AppScreen';
import { ScreenHeader } from '@/components/ScreenHeader';
import { Colors } from '@/constants/colors';
import { Ui } from '@/constants/theme';
import type { Listing } from '@/types/content';
import { useContentItems } from '@/utils/contentApi';
import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';

export default function TrainDetailsScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { items, loading, error } = useContentItems<Listing>('listing'); const train = items.find(item => item.id === id && item.serviceId === 'trains');
  return <AppScreen><ScrollView contentContainerStyle={styles.page}><ScreenHeader title="Your rail journey" subtitle="Check the route and service details before planning your trip." eyebrow="LEMONTRIP / TRAINS" onBack={() => router.canGoBack() ? router.back() : router.replace('/(tabs)/explore/trains')} /><View style={styles.card}><Ionicons name="train-outline" size={38} color={Colors.primary} /><Text style={styles.title}>{train?.name ?? (loading ? 'Loading train…' : error || 'Choose a train to continue')}</Text>{train ? <><Text style={styles.copy}>{train.detail}</Text><Text style={styles.price}>{train.price}</Text><View style={styles.notice}><Text style={styles.copy}>Check current fares, times, and seat availability with LemonTrip before booking this service. You can prepare passenger details now; this does not reserve a ticket.</Text></View><TouchableOpacity accessibilityRole="button" onPress={() => router.push('/contact')} style={styles.button}><Text style={styles.buttonText}>Ask about this journey</Text><Ionicons name="arrow-forward" size={18} color={Colors.primary} /></TouchableOpacity><TouchableOpacity accessibilityRole="button" onPress={() => { addToCart({ id: `train-${train.id}`, serviceName: "Trains", itemName: train.name, price: train.price }); router.push("/checkout"); }} style={[styles.button, { backgroundColor: Colors.surfaceMuted }]}><Text style={styles.buttonText}>Prepare passenger details</Text><Ionicons name="people-outline" size={18} color={Colors.primary} /></TouchableOpacity></> : <TouchableOpacity accessibilityRole="button" onPress={() => router.replace('/(tabs)/explore/trains')} style={styles.button}><Text style={styles.buttonText}>Search trains</Text></TouchableOpacity>}</View></ScrollView></AppScreen>;
}
const styles = StyleSheet.create({ page: { width: '100%', maxWidth: 760, alignSelf: 'center', paddingBottom: 24 }, card: { ...Ui.card, marginHorizontal: Ui.space.page, padding: 24 }, title: { fontFamily: 'Manrope', fontSize: 24, lineHeight: 31, fontWeight: '800', color: Colors.primary, marginTop: 16 }, copy: { fontFamily: 'Manrope', fontSize: 14, lineHeight: 23, color: Colors.textLight, marginTop: 8 }, price: { fontFamily: 'Manrope', fontSize: 25, fontWeight: '800', color: Colors.primary, marginTop: 20 }, notice: { backgroundColor: Colors.accentSoft, padding: 16, borderRadius: 18, marginTop: 18 }, button: { ...Ui.button, backgroundColor: Colors.accent, paddingHorizontal: 18, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 20 }, buttonText: { fontFamily: 'Manrope', color: Colors.primary, fontSize: 13, fontWeight: '800' } });
