import { Action, Copy, Empty, FeatureScreen, Panel, Row } from '@/components/FeatureScreen';
import { getAccessToken, useAuth } from '@/utils/authStore';
import { getVisaApplication, type VisaTracking } from '@/utils/visaService';
import { router, useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';
export default function VisaTrackingScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const user = useAuth();
  const [record, setRecord] = useState<{ actor: string; data: VisaTracking } | null>(null); const [error, setError] = useState(''); const [retry, setRetry] = useState(0);
  useEffect(() => { let active = true; const token = getAccessToken(); if (!user || !token) return; void getVisaApplication(id, token).then(data => { if (active) { setRecord({ actor: user.id, data }); setError(''); } }).catch(cause => { if (active) setError(cause instanceof Error ? cause.message : 'Application unavailable.'); }); return () => { active = false; }; }, [id, retry, user]);
  const application = record?.actor === user?.id && record?.data.id === id ? record.data : null;
  return <FeatureScreen title="Your visa journey" subtitle="Follow your application, one clear update at a time." eyebrow="VISA / APPLICATION STATUS">{!user ? <Empty title="Sign in to track your application" copy="Visa applications and personal documents are available only to the account that submitted them." action="Sign in" route="/login" icon="lock-closed-outline" /> : application ? <><Panel title={`${application.country} · ${application.visaType}`}><Copy>Reference: {application.id}</Copy><Copy>Applicant: {application.applicantName}</Copy><Copy>Submitted: {application.submittedDate}</Copy></Panel><Panel title="Latest application update"><Copy>{application.status}</Copy><Copy>This status comes from the visa service. Further updates will appear when your application progresses.</Copy><Action label="Refresh status" secondary onPress={() => setRetry(current => current + 1)} /></Panel><Panel title="Your application documents"><Copy>Open your application history to view the documents uploaded with this request.</Copy><Row title="View submitted documents" icon="document-attach-outline" route="/(tabs)/explore/visa/applications" /><Row title="Application support" icon="headset-outline" route={{ pathname: '/contact', params: { reference: id } }} /></Panel></> : <Panel title={error ? 'Application unavailable' : 'Checking your application…'}><Copy>{error || 'Loading your latest application details.'}</Copy>{error ? <Action label="Try again" onPress={() => setRetry(current => current + 1)} /> : null}<Action label="View applications" secondary onPress={() => router.replace('/(tabs)/explore/visa/applications')} /></Panel>}</FeatureScreen>;
}
