import { usePreferences } from '@/utils/preferencesStore';
import { Action, Copy, Empty, FeatureScreen, Field, Panel, Row } from '@/components/FeatureScreen';
import { Colors } from '@/constants/colors';
import { travelServices } from '@/constants/navigation';
import { useAuth } from '@/utils/authStore';
import { useAccountBookings } from '@/utils/accountBookings';
import { featureRequest } from '@/utils/featureApi';
import { isSearch, isTraveller, usePersonalItems, type SavedTraveller } from '@/utils/personalStore';
import { router, useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { Switch, Text, TouchableOpacity, View } from 'react-native';

const titles: Record<string, string> = { travellers: 'Saved travellers', 'saved-searches': 'Saved searches', 'recent-searches': 'Recent searches', notifications: 'Notifications', 'notification-settings': 'Notification settings', security: 'Security', language: 'Language', currency: 'Currency', 'edit-profile': 'Edit profile', 'personal-information': 'Personal information', about: 'About LemonTrip', search: 'Find your next journey', 'account-setup': 'Complete your profile', 'reset-password': 'Reset password', 'otp-verification': 'Verify your phone' };
export default function ManageScreen() {
  const { section } = useLocalSearchParams<{ section: string }>(); const user = useAuth(); const accountBookings = useAccountBookings(section === "notifications"); const bookings = accountBookings.bookings;
  const travellerStore = usePersonalItems('travellers', isTraveller); const searchStore = usePersonalItems('saved-searches', isSearch); const recentStore = usePersonalItems('recent-searches', isSearch);
  const [firstName, setFirstName] = useState(''); const [lastName, setLastName] = useState(''); const [editing, setEditing] = useState<string | null>(null); const [message, setMessage] = useState(''); const [query, setQuery] = useState('');
  const [profile, setProfile] = useState({ name: user?.name ?? '', email: user?.email ?? '', phone: user?.phone ?? '' });
  const preferences = usePreferences(); const { language, currency } = preferences.value; const updates = { bookings: preferences.value.bookings, offers: preferences.value.offers, emails: preferences.value.emails };
  const saveTraveller = async () => { if (!firstName.trim() || !lastName.trim()) { setMessage('Add both names as shown on the traveller’s identity document.'); return; } const item: SavedTraveller = { id: editing ?? `traveller-${Date.now()}`, firstName: firstName.trim(), lastName: lastName.trim() }; const next = editing ? travellerStore.items.map(old => old.id === editing ? item : old) : [...travellerStore.items, item]; if (await travellerStore.save(next)) { setFirstName(''); setLastName(''); setEditing(null); setMessage('Traveller saved on this device.'); } };
  const saveProfile = async () => { if (!profile.name.trim() || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(profile.email)) { setMessage('Enter your name and a valid email.'); return; } try { await featureRequest(process.env.EXPO_PUBLIC_ACCOUNT_API_URL, '/profile', { method: 'PATCH', body: profile }); setMessage('Your profile update was received.'); } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'Profile updates are unavailable.'); } };
  const searches = section === 'recent-searches' ? recentStore : searchStore;
  const visibleServices = travelServices.filter(service => `${service.title} ${service.description}`.toLowerCase().includes(query.toLowerCase()));
  let content;
  if (section === 'travellers') content = <><Panel title={editing ? 'Edit traveller' : 'Add a traveller'}><Copy>Save names on this device for easier booking. Use the name on the traveller’s identity document.</Copy><Field label="First name" value={firstName} onChangeText={setFirstName} autoCapitalize="words" /><Field label="Last name" value={lastName} onChangeText={setLastName} autoCapitalize="words" /><Action label={editing ? 'Save changes' : 'Save traveller'} onPress={() => void saveTraveller()} /></Panel>{travellerStore.items.map(item => <Panel key={item.id} title={`${item.firstName} ${item.lastName}`}><Action label="Edit traveller" secondary onPress={() => { setEditing(item.id); setFirstName(item.firstName); setLastName(item.lastName); }} /><Action label="Remove traveller" secondary onPress={() => void travellerStore.save(travellerStore.items.filter(old => old.id !== item.id))} /></Panel>)}{travellerStore.error ? <Copy>{travellerStore.error}</Copy> : null}</>;
  else if (section === 'saved-searches' || section === 'recent-searches') content = searches.items.length ? searches.items.map(item => <Panel key={item.id} title={item.label}><Copy>{item.service}</Copy><Action label="Search again" onPress={() => { const service = travelServices.find(service => service.shortTitle.toLowerCase() === item.service.toLowerCase()); if (service) router.push({ pathname: typeof service.route === 'string' ? service.route as '/(tabs)/explore/flights' : '/services', params: item.service.toLowerCase() === 'flights' ? { search: item.query } : { query: item.query } }); }} />{section === 'recent-searches' ? <Action label="Save search" secondary onPress={() => void searchStore.save([item, ...searchStore.items.filter(old => old.query !== item.query)])} /> : null}<Action label="Remove" secondary onPress={() => void searches.save(searches.items.filter(old => old.id !== item.id))} /></Panel>) : <Empty title={section === 'recent-searches' ? 'Start with a new journey' : 'Your favourite searches belong here'} copy="Recent searches can be saved and repeated from this device." action="Search travel services" route="/manage/search" icon="search-outline" />;
  else if (section === 'search') content = <><Panel><Field label="What are you planning?" value={query} onChangeText={setQuery} placeholder="Flights, hotels, rail, holidays…" /></Panel><Panel title="Choose a service">{visibleServices.map(service => <Row key={service.title} title={service.title} detail={service.description} icon={service.icon} route={service.route} />)}{!visibleServices.length ? <Copy>No matching service. Try another search.</Copy> : null}</Panel><Row title="Saved searches" route="/manage/saved-searches" icon="bookmark-outline" /></>;
  else if (section === 'notifications') content = <><Row title="Notification settings" icon="options-outline" route="/manage/notification-settings" />{bookings.length ? bookings.map(booking => <Panel key={booking.id} title={booking.itemName}><Copy>{booking.status ?? 'Booking update'} · {booking.tripDate ?? booking.bookedAt}</Copy><Action label="View booking" onPress={() => router.push({ pathname: '/booking/[id]', params: { id: booking.id } })} /></Panel>) : <Empty title={accountBookings.loading ? "Loading trip updates…" : "You’re all caught up"} copy={accountBookings.error || "Trip updates will appear here as your bookings progress."} icon="notifications-outline" />}</>;
  else if (section === 'notification-settings') content = <Panel title="Choose your updates">{(Object.keys(updates) as (keyof typeof updates)[]).map(key => <View key={key} style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', minHeight: 56 }}><Copy>{key === 'bookings' ? 'Booking updates' : key === 'offers' ? 'Offers and inspiration' : 'Email updates'}</Copy><Switch accessibilityLabel={`${key} updates`} value={updates[key]} onValueChange={value => void preferences.update({ [key]: value })} trackColor={{ false: Colors.borderStrong, true: Colors.primary }} /></View>)}<Copy>Your preferences are saved on this device. Delivery settings can be applied when account notifications are connected.</Copy></Panel>;
  else if (section === 'language' || section === 'currency') content = <Panel title={section === 'language' ? 'Display language' : 'Preferred currency'}>{(section === 'language' ? ['English'] : ['INR', 'USD', 'EUR', 'GBP']).map(option => <TouchableOpacity key={option} accessibilityRole="button" accessibilityState={{ selected: option === (section === 'language' ? language : currency) }} onPress={() => section === 'language' ? void preferences.update({ language: option }) : void preferences.update({ currency: option })} style={{ padding: 16, borderRadius: 16, backgroundColor: option === (section === 'language' ? language : currency) ? Colors.accentSoft : Colors.surface }}><Text style={{ fontFamily: 'Manrope', fontSize: 15, color: Colors.primary, fontWeight: '700' }}>{option}</Text></TouchableOpacity>)}<Copy>{section === 'language' ? 'English is currently available throughout the app. More translations are coming.' : 'Prices remain in the currency supplied by the provider. Currency conversion is not applied.'}</Copy></Panel>;
  else if (section === 'edit-profile' || section === 'account-setup') content = <Panel title="Your details">{(['name', 'email', 'phone'] as const).map(key => <Field key={key} label={key.charAt(0).toUpperCase() + key.slice(1)} value={profile[key]} onChangeText={value => setProfile(current => ({ ...current, [key]: value }))} keyboardType={key === 'email' ? 'email-address' : key === 'phone' ? 'phone-pad' : 'default'} autoCapitalize={key === 'email' ? 'none' : 'words'} />)}<Action label="Save profile" disabled={!user || !process.env.EXPO_PUBLIC_ACCOUNT_API_URL} onPress={() => void saveProfile()} /><Copy>{!user ? 'Sign in to manage your account.' : !process.env.EXPO_PUBLIC_ACCOUNT_API_URL ? 'Profile updates are unavailable right now. Contact support to update your details.' : 'Your verified contact details are used for booking updates.'}</Copy><Row title="Account support" route="/contact" icon="headset-outline" /></Panel>;
  else if (section === 'personal-information') content = <Panel title="Your account"><Copy>Name: {user?.name ?? 'Guest'}</Copy><Copy>Email: {user?.email ?? 'Not added'}</Copy><Copy>Phone: {user?.phone ?? 'Not added'}</Copy><Copy>Email verified: {user?.emailVerified ? 'Yes' : 'No'}</Copy><Action label={user ? 'Edit profile' : 'Sign in'} onPress={() => router.push(user ? '/manage/edit-profile' : '/login')} /></Panel>;
  else if (section === 'security' || section === 'reset-password' || section === 'otp-verification') content = <Panel title="Keep your account close"><Row title="Phone verification / OTP sign-in" icon="phone-portrait-outline" route={{ pathname: '/login', params: { mode: 'phone' } }} /><Row title="Password recovery" icon="key-outline" route="/reset-password" /><Row title="Privacy policy" icon="shield-checkmark-outline" route="/privacy" /><Copy>Your authentication and verification use the existing LemonTrip account service. Never share an OTP.</Copy></Panel>;
  else if (section === 'about') content = <Panel title="Travel smarter. Travel better."><Copy>LemonTrip brings flights, hotels, buses, trains, holiday packages, and visa assistance together in one clear travel experience.</Copy><Copy>Thoughtful escapes, transparent information, and support before and during your journey.</Copy><Row title="Explore travel services" route="/services" icon="compass-outline" /><Row title="Contact LemonTrip" route="/contact" icon="headset-outline" /><Row title="Terms & conditions" route="/terms" icon="document-text-outline" /></Panel>;
  else content = <Empty title="Your support conversations" copy="Verified support requests will appear here when support tracking is available. Contact our team for help with an existing request." icon="chatbubbles-outline" action="Contact support" route="/contact" />;
  return <FeatureScreen title={titles[section] ?? 'Your account'} subtitle="Made for the way you travel.">{content}{message ? <Copy>{message}</Copy> : null}{preferences.error ? <Copy>{preferences.error}</Copy> : null}</FeatureScreen>;
}

export function generateStaticParams() { return Object.keys(titles).map(section => ({ section })); }
