import { AppScreen } from '@/components/AppScreen';
import { ScreenHeader } from '@/components/ScreenHeader';
import { Colors } from '@/constants/colors';
import { Ui } from '@/constants/theme';
import { Ionicons } from '@expo/vector-icons';
import { router, type Href } from 'expo-router';
import type { ReactNode } from 'react';
import { ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View, type TextInputProps } from 'react-native';

export function FeatureScreen({ title, subtitle, eyebrow = 'YOUR LEMONTRIP', children }: { title: string; subtitle?: string; eyebrow?: string; children: ReactNode }) {
  return <AppScreen><ScrollView contentContainerStyle={featureStyles.page} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}><ScreenHeader title={title} subtitle={subtitle} eyebrow={eyebrow} onBack={() => router.canGoBack() ? router.back() : router.replace('/(tabs)')} /><View style={featureStyles.content}>{children}</View></ScrollView></AppScreen>;
}
export function Panel({ title, children }: { title?: string; children: ReactNode }) { return <View style={featureStyles.panel}>{title ? <Text style={featureStyles.title}>{title}</Text> : null}{children}</View>; }
export function Copy({ children }: { children: ReactNode }) { return <Text style={featureStyles.copy}>{children}</Text>; }
export function Field({ label, ...props }: TextInputProps & { label: string }) { return <View style={featureStyles.field}><Text style={featureStyles.label}>{label}</Text><TextInput accessibilityLabel={label} placeholderTextColor={Colors.textLight} {...props} style={[featureStyles.input, props.style]} /></View>; }
export function Action({ label, onPress, disabled, secondary = false }: { label: string; onPress: () => void; disabled?: boolean; secondary?: boolean }) { return <TouchableOpacity accessibilityRole="button" disabled={disabled} onPress={onPress} style={[featureStyles.action, secondary && featureStyles.secondary, disabled && { opacity: 0.45 }]}><Text style={featureStyles.actionText}>{label}</Text><Ionicons name="arrow-forward" size={18} color={Colors.primary} /></TouchableOpacity>; }
export function Row({ title, detail, icon = 'chevron-forward', route, onPress }: { title: string; detail?: string; icon?: React.ComponentProps<typeof Ionicons>['name']; route?: Href; onPress?: () => void }) { return <TouchableOpacity accessibilityRole={route || onPress ? "button" : undefined} disabled={!route && !onPress} onPress={onPress ?? (() => route && router.push(route))} style={featureStyles.row}><View style={featureStyles.rowIcon}><Ionicons name={icon} size={22} color={Colors.primary} /></View><View style={{ flex: 1, minWidth: 0 }}><Text style={featureStyles.rowTitle}>{title}</Text>{detail ? <Text style={featureStyles.rowDetail}>{detail}</Text> : null}</View>{route || onPress ? <Ionicons name="chevron-forward" size={17} color={Colors.textLight} /> : null}</TouchableOpacity>; }
export function Empty({ title, copy, icon = 'compass-outline', action, route }: { title: string; copy: string; icon?: React.ComponentProps<typeof Ionicons>['name']; action?: string; route?: Href }) { return <Panel><View style={featureStyles.emptyIcon}><Ionicons name={icon} size={34} color={Colors.primary} /></View><Text style={featureStyles.title}>{title}</Text><Copy>{copy}</Copy>{action && route ? <Action label={action} onPress={() => router.push(route)} /> : null}</Panel>; }
export const featureStyles = StyleSheet.create({ page: { width: '100%', maxWidth: 760, alignSelf: 'center', paddingBottom: 30 }, content: { paddingHorizontal: Ui.space.page, gap: 16 }, panel: { ...Ui.card, padding: 20, gap: 12 }, title: { ...Ui.typography.heading, color: Colors.primary }, copy: { ...Ui.typography.body, color: Colors.textLight }, field: { gap: 7 }, label: { fontFamily: 'Manrope', fontSize: 11, fontWeight: '800', color: Colors.primary }, input: { ...Ui.field, backgroundColor: Colors.background, borderWidth: 1, borderColor: Colors.border, fontFamily: 'Manrope', fontSize: 14, color: Colors.textDark, padding: 14 }, action: { ...Ui.button, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12, paddingHorizontal: Ui.space.page, backgroundColor: Colors.accent }, secondary: { backgroundColor: Colors.surface, borderWidth: 1, borderColor: Colors.border }, actionText: { ...Ui.typography.button, color: Colors.primary, flexShrink: 1 }, row: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 10, minHeight: 66 }, rowIcon: { width: 42, height: 42, borderRadius: 21, backgroundColor: Colors.surfaceMuted, alignItems: 'center', justifyContent: 'center' }, rowTitle: { fontFamily: 'Manrope', fontSize: 15, fontWeight: '800', color: Colors.primary }, rowDetail: { fontFamily: 'Manrope', fontSize: 12, lineHeight: 19, color: Colors.textLight, marginTop: 3 }, emptyIcon: { width: 74, height: 74, borderRadius: 37, backgroundColor: Colors.accentSoft, alignItems: 'center', justifyContent: 'center', marginBottom: 4 } });
