import { Action, Copy, Empty, FeatureScreen, Field, Panel, Row } from '@/components/FeatureScreen';
import { useAuth } from '@/utils/authStore';
import { featureRequest } from '@/utils/featureApi';
import { router, useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';

const titles: Record<string, string> = { transactions: 'Wallet transactions', 'add-money': 'Add money', 'payment-methods': 'Payment methods', coupons: 'Coupons & promo codes', 'payment-status': 'Payment status' };
export default function WalletSection() {
  const { section } = useLocalSearchParams<{ section: string }>(); const user = useAuth(); const [actor, setActor] = useState(''); const [amount, setAmount] = useState(''); const [reference, setReference] = useState(''); const [error, setError] = useState(''); const [transactions, setTransactions] = useState<{ id: string; description: string; amount: number; status: string; date: string }[]>([]);
  useEffect(() => { let active = true; if (section !== 'transactions' || !user || !process.env.EXPO_PUBLIC_WALLET_API_URL) return; void featureRequest<{ transactions: typeof transactions }>(process.env.EXPO_PUBLIC_WALLET_API_URL, '/wallet/transactions?page=1&limit=20').then(data => { if (!Array.isArray(data.transactions)) throw new Error('Transactions could not be verified.'); if (active) { setActor(user.id); setTransactions(data.transactions.filter(item => typeof item.id === 'string' && typeof item.description === 'string' && Number.isFinite(item.amount) && typeof item.status === 'string' && typeof item.date === 'string')); } }).catch(cause => { if (active) setError(cause instanceof Error ? cause.message : 'Transactions unavailable.'); }); return () => { active = false; }; }, [section, user]);
  return <FeatureScreen title={titles[section] ?? 'Wallet'} subtitle="Keep every payment clear and easy to follow." eyebrow="LEMONTRIP WALLET">{section === 'add-money' ? <Panel title="How much would you like to add?"><Field label="Amount (INR)" value={amount} onChangeText={setAmount} keyboardType="decimal-pad" placeholder="Enter amount" /><Copy>Secure wallet top-ups are not available in this app yet. Your balance changes only after a verified payment.</Copy><Action label="Continue to secure payment" disabled onPress={() => {}} /><Action label="Access website wallet" secondary onPress={() => router.replace('/wallet')} /></Panel> : section === 'payment-methods' ? <Panel title="Ways to pay"><Row title="UPI" detail="Available when secure checkout is connected" icon="phone-portrait-outline" /><Row title="Credit / debit card" detail="Card details are handled by the payment provider" icon="card-outline" /><Row title="Net banking" detail="Pay securely with your bank" icon="business-outline" /><Row title="LemonTrip wallet" detail="Use a verified balance" icon="wallet-outline" /><Copy>Payment methods will become selectable when a secure payment provider is available.</Copy></Panel> : section === 'coupons' ? <><Panel title="Have a promo code?"><Field label="Promo code" value={reference} onChangeText={setReference} autoCapitalize="characters" placeholder="Enter code" /><Copy>Coupon eligibility is verified at checkout. Browse offers for the full terms.</Copy><Action label="Browse offers" onPress={() => router.push('/offers')} /></Panel></> : section === 'payment-status' ? <Panel title="Check a payment"><Field label="Payment reference" value={reference} onChangeText={setReference} placeholder="Reference from your payment receipt" /><Copy>No verified payment result is available on this device. Contact support with your reference for help.</Copy><Action label="Contact payment support" onPress={() => router.push('/contact')} /></Panel> : transactions.length && user && actor === user.id ? transactions.map(item => <Panel key={item.id} title={item.description}><Copy>{item.status} · {item.date}</Copy><Copy>{item.amount.toLocaleString('en-IN')}</Copy></Panel>) : <Empty title={!user ? 'Sign in to see your transactions' : 'Transactions unavailable'} copy={error || 'Verified wallet activity will appear here when your wallet service is available.'} icon="receipt-outline" action={!user ? 'Sign in' : 'Wallet support'} route={!user ? '/login' : '/contact'} />}</FeatureScreen>;
}

export function generateStaticParams() { return Object.keys(titles).map(section => ({ section })); }
