import { AppScreen } from '@/components/AppScreen';
import { ScreenHeader } from '@/components/ScreenHeader';
import { Colors } from '@/constants/colors';
import { Ui } from '@/constants/theme';
import type { Offer } from '@/data/offers';
import { getOfferValidity, loadOffers, type OfferSource } from '@/utils/offerApi';
import { Ionicons } from '@expo/vector-icons';
import * as Clipboard from 'expo-clipboard';
import { router, useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';
import { Image, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';

export default function OfferDetailsScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const [offer, setOffer] = useState<Offer | null>(null); const [source, setSource] = useState<OfferSource | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [copied, setCopied] = useState(false);
  useEffect(() => { let active = true; void loadOffers().then(result => { if (active) { setOffer(result.offers.find(item => item.id === id) ?? null); setSource(result.source); } }).catch(cause => { if (active) setError(cause instanceof Error ? cause.message : 'Could not load this offer.'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [id]);
  const copy = async () => { if (!offer?.code) return; try { await Clipboard.setStringAsync(offer.code); setCopied(true); } catch { setError('Copy is unavailable. You can select the code and copy it manually.'); } };
  return <AppScreen><ScrollView contentContainerStyle={styles.page}><ScreenHeader title="A little extra for your trip." subtitle="Read the details before choosing an offer." eyebrow="LEMONTRIP / OFFERS" onBack={() => router.canGoBack() ? router.back() : router.replace('/offers')} />{offer ? <View style={styles.card}><Image source={{ uri: offer.image }} style={styles.image} /><View style={styles.body}><Text style={styles.label}>{offer.category}</Text><Text style={styles.title}>{offer.title}</Text><Text style={styles.copy}>{offer.description}</Text><Text style={styles.notice}>{source === 'demo' ? 'Preview offer · availability is unverified' : `Status: ${getOfferValidity(offer.validUntil)}`}</Text>{offer.code ? <TouchableOpacity accessibilityRole="button" accessibilityLabel="Copy coupon code" onPress={() => void copy()} style={styles.coupon}><Text selectable style={styles.code}>{offer.code}</Text><Ionicons name={copied ? 'checkmark' : 'copy-outline'} size={20} color={Colors.primary} /><Text style={styles.label}>{copied ? 'Copied' : 'Copy'}</Text></TouchableOpacity> : null}<Text style={styles.heading}>Terms and conditions</Text><Text style={styles.copy}>{offer.terms ?? 'Terms have not been supplied for this offer. Contact LemonTrip to check availability before booking.'}</Text>{offer.validUntil ? <Text style={styles.copy}>Valid until {offer.validUntil}</Text> : null}<TouchableOpacity accessibilityRole="button" onPress={() => router.push('/services')} style={styles.button}><Text style={styles.buttonText}>Explore travel services</Text><Ionicons name="arrow-forward" size={18} color={Colors.primary} /></TouchableOpacity></View></View> : <View style={styles.card}><View style={styles.body}><Text style={styles.title}>{loading ? 'Loading offer…' : error || 'Offer not found'}</Text></View></View>}{error && offer ? <Text style={styles.error}>{error}</Text> : null}</ScrollView></AppScreen>;
}
const styles = StyleSheet.create({ page: { width: '100%', maxWidth: 760, alignSelf: 'center', paddingBottom: 24 }, card: { ...Ui.card, marginHorizontal: 18, overflow: 'hidden' }, image: { width: '100%', height: 220, backgroundColor: Colors.surfaceMuted }, body: { padding: 20 }, label: { fontFamily: 'Manrope', fontSize: 11, fontWeight: '800', color: Colors.primary }, title: { fontFamily: 'Manrope', fontSize: 24, lineHeight: 31, fontWeight: '800', color: Colors.primary, marginTop: 8 }, copy: { fontFamily: 'Manrope', fontSize: 14, lineHeight: 23, color: Colors.textLight, marginTop: 12 }, notice: { fontFamily: 'Manrope', fontSize: 12, color: Colors.textLight, marginTop: 16 }, coupon: { borderWidth: 1, borderStyle: 'dashed', borderColor: Colors.borderStrong, borderRadius: 18, backgroundColor: Colors.accentSoft, padding: 16, flexDirection: 'row', gap: 12, alignItems: 'center', marginTop: 18 }, code: { flex: 1, fontFamily: 'Manrope', fontSize: 20, fontWeight: '800', color: Colors.primary }, heading: { fontFamily: 'Manrope', fontSize: 18, fontWeight: '800', color: Colors.primary, marginTop: 24 }, button: { ...Ui.button, backgroundColor: Colors.accent, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, paddingHorizontal: 18, marginTop: 24 }, buttonText: { fontFamily: 'Manrope', fontSize: 13, fontWeight: '800', color: Colors.primary }, error: { fontFamily: 'Manrope', fontSize: 13, color: Colors.error, margin: 18 } });
